In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/ADMIN/Downloads/StudentPerformanceFactors.csv")
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [3]:
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

(6607, 20)
Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB
None
       Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000
mean       19.975329    79.977448      7.02906        75.070531
std         5.990594    11.547475      1.46812        14.399784
min         1.000000    60.000000      4.00000        50.000000
25%        16.000000    70.000000      6.00000        63.000000
50%        20.000000    80.000000      7.00000        75.000000
75%        24.000000    90.000000      8.00000        88.000000
max        44.000000   100.000000     10.00000       100.000000

       Tutoring_Sessions  Physical_Activity   Exam_Score
count        6607.000000        6607.000000  6607.000000
mean            1.493719           2.967610    67.235659
std             1.230570           1.031231     3.890456
min             0.000000           0.000000    55.000000
25%             1.000000           2.000000    65.000000
50%             1.000000           3.000000    67.000000
75%             2.000000           4.000000    69.000000
max             8.000000           6.000000   101.000000

In [4]:
print(df.isnull().sum())

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [5]:
df['average_score'] = df[['Previous_Scores', 'Exam_Score']].mean(axis=1)
print(df.head())

   Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0             23          84                  Low                High
1             19          64                  Low              Medium
2             24          98               Medium              Medium
3             29          89                  Low              Medium
4             19          92               Medium              Medium

  Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level  \
0                         No            7               73              Low
1                         No            8               59              Low
2                        Yes            7               91           Medium
3                        Yes            8               98           Medium
4                        Yes            6               65           Medium

  Internet_Access  Tutoring_Sessions  ... Teacher_Quality School_Type  \
0             Yes                  0  ...          Medium      Public
1             Yes                  2  ...          Medium      Public
2             Yes                  2  ...          Medium      Public
3             Yes                  1  ...          Medium      Public
4             Yes                  3  ...            High      Public

  Peer_Influence Physical_Activity  Learning_Disabilities  \
0       Positive                 3                     No
1       Negative                 4                     No
2        Neutral                 4                     No
3       Negative                 4                     No
4        Neutral                 4                     No

  Parental_Education_Level Distance_from_Home  Gender Exam_Score  \
0              High School               Near    Male         67
1                  College           Moderate  Female         61
2             Postgraduate               Near    Male         74
3              High School           Moderate    Male         71
4                  College               Near  Female         70

   average_score
0           70.0
1           60.0
2           82.5
3           84.5
4           67.5

[5 rows x 21 columns]

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns)

Index(['hours_studied', 'attendance', 'parental_involvement',
       'access_to_resources', 'extracurricular_activities', 'sleep_hours',
       'previous_scores', 'motivation_level', 'internet_access',
       'tutoring_sessions', 'family_income', 'teacher_quality', 'school_type',
       'peer_influence', 'physical_activity', 'learning_disabilities',
       'parental_education_level', 'distance_from_home', 'gender',
       'exam_score', 'average_score'],
      dtype='object')

In [7]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   hours_studied               6607 non-null   int64
 1   attendance                  6607 non-null   int64
 2   parental_involvement        6607 non-null   object
 3   access_to_resources         6607 non-null   object
 4   extracurricular_activities  6607 non-null   object
 5   sleep_hours                 6607 non-null   int64
 6   previous_scores             6607 non-null   int64
 7   motivation_level            6607 non-null   object
 8   internet_access             6607 non-null   object
 9   tutoring_sessions           6607 non-null   int64
 10  family_income               6607 non-null   object
 11  teacher_quality             6529 non-null   object
 12  school_type                 6607 non-null   object
 13  peer_influence              6607 non-null   object
 14  physical_activity           6607 non-null   int64
 15  learning_disabilities       6607 non-null   object
 16  parental_education_level    6517 non-null   object
 17  distance_from_home          6540 non-null   object
 18  gender                      6607 non-null   object
 19  exam_score                  6607 non-null   int64
 20  average_score               6607 non-null   float64
dtypes: float64(1), int64(7), object(13)
memory usage: 1.1+ MB
None
hours_studied                  0
attendance                     0
parental_involvement           0
access_to_resources            0
extracurricular_activities     0
sleep_hours                    0
previous_scores                0
motivation_level               0
internet_access                0
tutoring_sessions              0
family_income                  0
teacher_quality               78
school_type                    0
peer_influence                 0
physical_activity              0
learning_disabilities          0
parental_education_level      90
distance_from_home            67
gender                         0
exam_score                     0
average_score                  0
dtype: int64

In [8]:
for col in df.select_dtypes(include='number'):
    df[col] = df[col].fillna(df[col].median())

In [9]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
if 'previous_score' in df.columns and 'exam_score' in df.columns:
    df['average_score'] = df[['previous_score', 'exam_score']].mean(axis=1)

In [11]:
if 'hours_studied' in df.columns and 'attendance' in df.columns:
    df['study_efficiency'] = df['hours_studied'] * df['attendance']

In [12]:
df = pd.get_dummies(df, drop_first=True)

In [13]:
print(df.head())
print(df.info())

   hours_studied  attendance  sleep_hours  previous_scores  tutoring_sessions  \
0             23          84            7               73                  0
1             19          64            8               59                  2
2             24          98            7               91                  2
3             29          89            8               98                  1
4             19          92            6               65                  3

   physical_activity  exam_score  average_score  study_efficiency  \
0                  3          67           70.0              1932
1                  4          61           60.0              1216
2                  4          74           82.5              2352
3                  4          71           84.5              2581
4                  4          70           67.5              1748

   parental_involvement_Low  ...  teacher_quality_Medium  school_type_Public  \
0                      True  ...                    True                True
1                      True  ...                    True                True
2                     False  ...                    True                True
3                      True  ...                    True                True
4                     False  ...                   False                True

   peer_influence_Neutral  peer_influence_Positive  learning_disabilities_Yes  \
0                   False                     True                      False
1                   False                    False                      False
2                    True                    False                      False
3                   False                    False                      False
4                    True                    False                      False

   parental_education_level_High School  \
0                                  True
1                                 False
2                                 False
3                                  True
4                                 False

   parental_education_level_Postgraduate  distance_from_home_Moderate  \
0                                  False                        False
1                                  False                         True
2                                   True                        False
3                                  False                         True
4                                  False                        False

   distance_from_home_Near  gender_Male
0                     True         True
1                    False        False
2                     True         True
3                    False         True
4                     True        False

[5 rows x 30 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   hours_studied                          6607 non-null   int64
 1   attendance                             6607 non-null   int64
 2   sleep_hours                            6607 non-null   int64
 3   previous_scores                        6607 non-null   int64
 4   tutoring_sessions                      6607 non-null   int64
 5   physical_activity                      6607 non-null   int64
 6   exam_score                             6607 non-null   int64
 7   average_score                          6607 non-null   float64
 8   study_efficiency                       6607 non-null   int64
 9   parental_involvement_Low               6607 non-null   bool
 10  parental_involvement_Medium            6607 non-null   bool
 11  access_to_resources_Low                6607 non-null   bool
 12  access_to_resources_Medium             6607 non-null   bool
 13  extracurricular_activities_Yes         6607 non-null   bool
 14  motivation_level_Low                   6607 non-null   bool
 15  motivation_level_Medium                6607 non-null   bool
 16  internet_access_Yes                    6607 non-null   bool
 17  family_income_Low                      6607 non-null   bool
 18  family_income_Medium                   6607 non-null   bool
 19  teacher_quality_Low                    6607 non-null   bool
 20  teacher_quality_Medium                 6607 non-null   bool
 21  school_type_Public                     6607 non-null   bool
 22  peer_influence_Neutral                 6607 non-null   bool
 23  peer_influence_Positive                6607 non-null   bool
 24  learning_disabilities_Yes              6607 non-null   bool
 25  parental_education_level_High School   6607 non-null   bool
 26  parental_education_level_Postgraduate  6607 non-null   bool
 27  distance_from_home_Moderate            6607 non-null   bool
 28  distance_from_home_Near                6607 non-null   bool
 29  gender_Male                            6607 non-null   bool
dtypes: bool(21), float64(1), int64(8)
memory usage: 600.2 KB
None

In [14]:
print(df.columns)

Index(['hours_studied', 'attendance', 'sleep_hours', 'previous_scores',
       'tutoring_sessions', 'physical_activity', 'exam_score', 'average_score',
       'study_efficiency', 'parental_involvement_Low',
       'parental_involvement_Medium', 'access_to_resources_Low',
       'access_to_resources_Medium', 'extracurricular_activities_Yes',
       'motivation_level_Low', 'motivation_level_Medium',
       'internet_access_Yes', 'family_income_Low', 'family_income_Medium',
       'teacher_quality_Low', 'teacher_quality_Medium', 'school_type_Public',
       'peer_influence_Neutral', 'peer_influence_Positive',
       'learning_disabilities_Yes', 'parental_education_level_High School',
       'parental_education_level_Postgraduate', 'distance_from_home_Moderate',
       'distance_from_home_Near', 'gender_Male'],
      dtype='object')

In [15]:
df.columns = df.columns.str.strip()

In [16]:
for col in df.columns:
    print(f"'{col}'")

'hours_studied'
'attendance'
'sleep_hours'
'previous_scores'
'tutoring_sessions'
'physical_activity'
'exam_score'
'average_score'
'study_efficiency'
'parental_involvement_Low'
'parental_involvement_Medium'
'access_to_resources_Low'
'access_to_resources_Medium'
'extracurricular_activities_Yes'
'motivation_level_Low'
'motivation_level_Medium'
'internet_access_Yes'
'family_income_Low'
'family_income_Medium'
'teacher_quality_Low'
'teacher_quality_Medium'
'school_type_Public'
'peer_influence_Neutral'
'peer_influence_Positive'
'learning_disabilities_Yes'
'parental_education_level_High School'
'parental_education_level_Postgraduate'
'distance_from_home_Moderate'
'distance_from_home_Near'
'gender_Male'

In [17]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].astype('string')

In [18]:
print(df.dtypes)

hours_studied                              int64
attendance                                 int64
sleep_hours                                int64
previous_scores                            int64
tutoring_sessions                          int64
physical_activity                          int64
exam_score                                 int64
average_score                            float64
study_efficiency                           int64
parental_involvement_Low                    bool
parental_involvement_Medium                 bool
access_to_resources_Low                     bool
access_to_resources_Medium                  bool
extracurricular_activities_Yes              bool
motivation_level_Low                        bool
motivation_level_Medium                     bool
internet_access_Yes                         bool
family_income_Low                           bool
family_income_Medium                        bool
teacher_quality_Low                         bool
teacher_quality_Medium                      bool
school_type_Public                          bool
peer_influence_Neutral                      bool
peer_influence_Positive                     bool
learning_disabilities_Yes                   bool
parental_education_level_High School        bool
parental_education_level_Postgraduate       bool
distance_from_home_Moderate                 bool
distance_from_home_Near                     bool
gender_Male                                 bool
dtype: object

In [19]:
print(df.dtypes)
print(df.head())

hours_studied                              int64
attendance                                 int64
sleep_hours                                int64
previous_scores                            int64
tutoring_sessions                          int64
physical_activity                          int64
exam_score                                 int64
average_score                            float64
study_efficiency                           int64
parental_involvement_Low                    bool
parental_involvement_Medium                 bool
access_to_resources_Low                     bool
access_to_resources_Medium                  bool
extracurricular_activities_Yes              bool
motivation_level_Low                        bool
motivation_level_Medium                     bool
internet_access_Yes                         bool
family_income_Low                           bool
family_income_Medium                        bool
teacher_quality_Low                         bool
teacher_quality_Medium                      bool
school_type_Public                          bool
peer_influence_Neutral                      bool
peer_influence_Positive                     bool
learning_disabilities_Yes                   bool
parental_education_level_High School        bool
parental_education_level_Postgraduate       bool
distance_from_home_Moderate                 bool
distance_from_home_Near                     bool
gender_Male                                 bool
dtype: object
   hours_studied  attendance  sleep_hours  previous_scores  tutoring_sessions  \
0             23          84            7               73                  0
1             19          64            8               59                  2
2             24          98            7               91                  2
3             29          89            8               98                  1
4             19          92            6               65                  3

   physical_activity  exam_score  average_score  study_efficiency  \
0                  3          67           70.0              1932
1                  4          61           60.0              1216
2                  4          74           82.5              2352
3                  4          71           84.5              2581
4                  4          70           67.5              1748

   parental_involvement_Low  ...  teacher_quality_Medium  school_type_Public  \
0                      True  ...                    True                True
1                      True  ...                    True                True
2                     False  ...                    True                True
3                      True  ...                    True                True
4                     False  ...                   False                True

   peer_influence_Neutral  peer_influence_Positive  learning_disabilities_Yes  \
0                   False                     True                      False
1                   False                    False                      False
2                    True                    False                      False
3                   False                    False                      False
4                    True                    False                      False

   parental_education_level_High School  \
0                                  True
1                                 False
2                                 False
3                                  True
4                                 False

   parental_education_level_Postgraduate  distance_from_home_Moderate  \
0                                  False                        False
1                                  False                         True
2                                   True                        False
3                                  False                         True
4                                  False                        False

   distance_from_home_Near  gender_Male
0                     True         True
1                    False        False
2                     True         True
3                    False         True
4                     True        False

[5 rows x 30 columns]

In [20]:
df = df.fillna('Unknown')

In [21]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [22]:
print(df['Internet_Access'].unique())
print(df['Learning_Disabilities'].unique())
print(df['Extracurricular_Activities'].unique())

KeyError: 'Internet_Access'

In [ ]:
df['Internet_Access'] = df['Internet_Access'].map({'Yes': 1, 'No': 0})
df['Learning_Disabilities'] = df['Learning_Disabilities'].map({'Yes': 1, 'No': 0})
df['Extracurricular_Activities'] = df['Extracurricular_Activities'].map({'Yes': 1,'No': 0})

In [ ]:
print(df[['Internet_Access', 'Learning_Disabilities','Extracurricular_Activities']].head())

   Internet_Access  Learning_Disabilities  Extracurricular_Activities
0              NaN                    NaN                           0
1              NaN                    NaN                           0
2              NaN                    NaN                           1
3              NaN                    NaN                           1
4              NaN                    NaN                           1

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Internet_Access'] = le.fit_transform(df['Internet_Access'])
df['Learning_Disabilities'] = le.fit_transform(df['Learning_Disabilities'])
df['Extracurricular_Activities'] = le.fit_transform(df['Extracurricular_Activities'])

In [ ]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,0,7,73,Low,0,0,Low,Medium,Public,Positive,3,0,High School,Near,Male,67
1,19,64,Low,Medium,0,8,59,Low,0,2,Medium,Medium,Public,Negative,4,0,College,Moderate,Female,61
2,24,98,Medium,Medium,1,7,91,Medium,0,2,Medium,Medium,Public,Neutral,4,0,Postgraduate,Near,Male,74
3,29,89,Low,Medium,1,8,98,Medium,0,1,Medium,Medium,Public,Negative,4,0,High School,Moderate,Male,71
4,19,92,Medium,Medium,1,6,65,Medium,0,3,Medium,High,Public,Neutral,4,0,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,0,7,76,Medium,0,1,High,Medium,Public,Positive,2,0,High School,Near,Female,68
6603,23,76,High,Medium,0,8,81,Medium,0,3,Low,High,Public,Positive,2,0,High School,Near,Female,69
6604,20,90,Medium,Low,1,6,65,Low,0,3,Low,Medium,Public,Negative,2,0,Postgraduate,Near,Female,68
6605,10,86,High,High,1,6,91,High,0,2,Low,Medium,Private,Positive,3,0,High School,Far,Female,68
6606,15,67,Medium,Low,1,9,94,Medium,0,0,Medium,Medium,Public,Positive,4,0,Postgraduate,Near,Male,64

In [ ]:
new_df = df[['Hours_Studied','Attendance','Sleep_Hours','Previous_Scores','Internet_Access','Physical_Activity','Learning_Disabilities','Exam_Score']]
new_df.to_csv('retail_cleaned2.csv',index=False)

In [ ]:
import pandas as pd
check_df = pd.read_csv('retail_cleaned2.csv')
print(check_df.head())
print(check_df.shape)
print(check_df.info())

   Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  Internet_Access  \
0             23          84            7               73                0
1             19          64            8               59                0
2             24          98            7               91                0
3             29          89            8               98                0
4             19          92            6               65                0

   Physical_Activity  Learning_Disabilities  Exam_Score
0                  3                      0          67
1                  4                      0          61
2                  4                      0          74
3                  4                      0          71
4                  4                      0          70
(6607, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Hours_Studied          6607 non-null   int64
 1   Attendance             6607 non-null   int64
 2   Sleep_Hours            6607 non-null   int64
 3   Previous_Scores        6607 non-null   int64
 4   Internet_Access        6607 non-null   int64
 5   Physical_Activity      6607 non-null   int64
 6   Learning_Disabilities  6607 non-null   int64
 7   Exam_Score             6607 non-null   int64
dtypes: int64(8)
memory usage: 413.1 KB
None

In [ ]:
print(new_df.isnull().sum())
print(new_df.describe())
print(new_df['Internet_Access'].value_counts())

Hours_Studied            0
Attendance               0
Sleep_Hours              0
Previous_Scores          0
Internet_Access          0
Physical_Activity        0
Learning_Disabilities    0
Exam_Score               0
dtype: int64
       Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000
mean       19.975329    79.977448      7.02906        75.070531
std         5.990594    11.547475      1.46812        14.399784
min         1.000000    60.000000      4.00000        50.000000
25%        16.000000    70.000000      6.00000        63.000000
50%        20.000000    80.000000      7.00000        75.000000
75%        24.000000    90.000000      8.00000        88.000000
max        44.000000   100.000000     10.00000       100.000000

       Internet_Access  Physical_Activity  Learning_Disabilities   Exam_Score
count           6607.0        6607.000000                 6607.0  6607.000000
mean               0.0           2.967610                    0.0    67.235659
std                0.0           1.031231                    0.0     3.890456
min                0.0           0.000000                    0.0    55.000000
25%                0.0           2.000000                    0.0    65.000000
50%                0.0           3.000000                    0.0    67.000000
75%                0.0           4.000000                    0.0    69.000000
max                0.0           6.000000                    0.0   101.000000
Internet_Access
0    6607
Name: count, dtype: int64

In [ ]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,0,7,73,Low,0,0,Low,Medium,Public,Positive,3,0,High School,Near,Male,67
1,19,64,Low,Medium,0,8,59,Low,0,2,Medium,Medium,Public,Negative,4,0,College,Moderate,Female,61
2,24,98,Medium,Medium,1,7,91,Medium,0,2,Medium,Medium,Public,Neutral,4,0,Postgraduate,Near,Male,74
3,29,89,Low,Medium,1,8,98,Medium,0,1,Medium,Medium,Public,Negative,4,0,High School,Moderate,Male,71
4,19,92,Medium,Medium,1,6,65,Medium,0,3,Medium,High,Public,Neutral,4,0,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,0,7,76,Medium,0,1,High,Medium,Public,Positive,2,0,High School,Near,Female,68
6603,23,76,High,Medium,0,8,81,Medium,0,3,Low,High,Public,Positive,2,0,High School,Near,Female,69
6604,20,90,Medium,Low,1,6,65,Low,0,3,Low,Medium,Public,Negative,2,0,Postgraduate,Near,Female,68
6605,10,86,High,High,1,6,91,High,0,2,Low,Medium,Private,Positive,3,0,High School,Far,Female,68
6606,15,67,Medium,Low,1,9,94,Medium,0,0,Medium,Medium,Public,Positive,4,0,Postgraduate,Near,Male,64

In [ ]:
print(df.columns)

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score', 'Parental_involvement'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip().str.replace("","_")

In [ ]:
df = df.drop(columns=[
     'Parental_Involvement',
     'Access_to_Resources'
     'Motivation_Level'
     'Family_Income'
     'Peer_Influence'
     'Parental_Education_Level'
     'Distance_from_Home'
],errors='ignore')

In [ ]:
df

,_H_o_u_r_s___S_t_u_d_i_e_d_,_A_t_t_e_n_d_a_n_c_e_,_P_a_r_e_n_t_a_l___I_n_v_o_l_v_e_m_e_n_t_,_A_c_c_e_s_s___t_o___R_e_s_o_u_r_c_e_s_,_E_x_t_r_a_c_u_r_r_i_c_u_l_a_r___A_c_t_i_v_i_t_i_e_s_,_S_l_e_e_p___H_o_u_r_s_,_P_r_e_v_i_o_u_s___S_c_o_r_e_s_,_M_o_t_i_v_a_t_i_o_n___L_e_v_e_l_,_I_n_t_e_r_n_e_t___A_c_c_e_s_s_,_T_u_t_o_r_i_n_g___S_e_s_s_i_o_n_s_,...,_T_e_a_c_h_e_r___Q_u_a_l_i_t_y_,_S_c_h_o_o_l___T_y_p_e_,_P_e_e_r___I_n_f_l_u_e_n_c_e_,_P_h_y_s_i_c_a_l___A_c_t_i_v_i_t_y_,_L_e_a_r_n_i_n_g___D_i_s_a_b_i_l_i_t_i_e_s_,_P_a_r_e_n_t_a_l___E_d_u_c_a_t_i_o_n___L_e_v_e_l_,_D_i_s_t_a_n_c_e___f_r_o_m___H_o_m_e_,_G_e_n_d_e_r_,_E_x_a_m___S_c_o_r_e_,_P_a_r_e_n_t_a_l___i_n_v_o_l_v_e_m_e_n_t_
0,23,84,0,2,0,7,73,Low,0,0,...,Medium,Public,Positive,3,0,High School,Near,Male,67,0
1,19,64,0,1,0,8,59,Low,0,2,...,Medium,Public,Negative,4,0,College,Moderate,Female,61,0
2,24,98,1,1,1,7,91,Medium,0,2,...,Medium,Public,Neutral,4,0,Postgraduate,Near,Male,74,1
3,29,89,0,1,1,8,98,Medium,0,1,...,Medium,Public,Negative,4,0,High School,Moderate,Male,71,0
4,19,92,1,1,1,6,65,Medium,0,3,...,High,Public,Neutral,4,0,College,Near,Female,70,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,2,1,0,7,76,Medium,0,1,...,Medium,Public,Positive,2,0,High School,Near,Female,68,2
6603,23,76,2,1,0,8,81,Medium,0,3,...,High,Public,Positive,2,0,High School,Near,Female,69,2
6604,20,90,1,0,1,6,65,Low,0,3,...,Medium,Public,Negative,2,0,Postgraduate,Near,Female,68,1
6605,10,86,2,2,1,6,91,High,0,2,...,Medium,Private,Positive,3,0,High School,Far,Female,68,2
6606,15,67,1,0,1,9,94,Medium,0,0,...,Medium,Public,Positive,4,0,Postgraduate,Near,Male,64,1